[features]
seeds = false
skip-lint = false

[programs.localnet]
program = "H24WUvSjhgC5GJx8DaDtqvySTAjXMb2pj6VXCKPzTdLw"

[registry]
url = "https://beta.solpg.io/"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/nhanvo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
